-- Generated by the database client.
CREATE TABLE product(
    id SERIAL NOT NULL,
    name varchar(255),
    price numeric,
    quantity integer,
    available boolean,
    order_id integer,
    PRIMARY KEY(id),
    CONSTRAINT product_order_id_fkey FOREIGN key(order_id) REFERENCES orderdetail(id)
);