-- Generated by the database client.
CREATE TABLE product_productcategory(
    product_id integer NOT NULL,
    category_id integer NOT NULL,
    PRIMARY KEY(product_id,category_id),
    CONSTRAINT product_productcategory_product_id_fkey FOREIGN key(product_id) REFERENCES product(id),
    CONSTRAINT product_productcategory_category_id_fkey FOREIGN key(category_id) REFERENCES productcategory(id)
);